---
kind: pipeline
name: ci

steps:
  - name: install
    image: iknpx/archnode
    commands:
      - yarn --silent
    when:
      branch:
        - master
      event:
        - push

  - name: build
    image: iknpx/archnode
    environment:
      NODE_ENV: production
      # TODO: move to host drone envs
      API: https://api.abme.tk
      SESSION: abme_app_token
    commands:
      - yarn dist
    when:
      branch:
        - master
      event:
        - push

  - name: deploy
    image: iknpx/archnode
    environment:
      ROOT_KEY:
        from_secret: root_key
    commands:
      - yarn deploy
    when:
      branch:
        - master
      event:
        - push
